# synced from apix-actions/.github/workflows/issue-reopened.yaml
name: Reopen Jira Ticket on Issue Reopen

on:
  issues:
    types: [reopened]

permissions: {}

jobs:
  reopen-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-reopened.yaml@63d846315cbb3b905482ee8f32c88188032daf28
    secrets: inherit