name: Close Jira Ticket on Issue Close

on:
  issues:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    uses: mongodb/apix-action/.github/workflows/_issue-closed.yaml@main
    secrets: inherit