# synced from apix-actions/.github/workflows/issue-closed.yaml
name: Close Jira Ticket on Issue Close

on:
  issues:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-closed.yaml@09da7906fa2304420acdcf0e92fb218e6333051c
    secrets: inherit