# synced from apix-actions/.github/workflows/issue-opened.yaml
name: Create Jira Ticket for New Issues

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  create-jira:
    permissions:
      contents: read
      issues: write
    uses: mongodb/apix-action/.github/workflows/_issue-opened.yaml@b9d203ba30a17b2cae54f9bb2265b4142af38fec
    secrets: inherit