# synced from apix-actions/.github/workflows/issue-reopened.yaml
name: Reopen Jira Ticket on Issue Reopen

on:
  issues:
    types: [reopened]

permissions: {}

jobs:
  reopen-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-reopened.yaml@58bed0c5e3362646ee6450a40f1bfa323be50991
    secrets:
      op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}