# synced from apix-actions/.github/workflows/issue-opened.yaml
name: Create Jira Ticket for New Issues

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  create-jira:
    permissions:
      contents: read
      issues: write
    uses: mongodb/apix-action/.github/workflows/_issue-opened.yaml@f7d2400a387dea2661651b14bbaf8c8f46c8bf66 # main
    secrets: inherit