# synced from apix-actions/.github/workflows/issue-reopened.yaml
name: Reopen Jira Ticket on Issue Reopen

on:
  issues:
    types: [reopened]

permissions: {}

jobs:
  reopen-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-reopened.yaml@5a8a84233f754cf95f52502d70b508792ac77159 # main
    secrets: inherit